version: '2'

services:
  mysql:
    image: mysql:5
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: boom
      MYSQL_DATABASE: test

  consul:
    image: consul
    ports:
      - "8500:8500"
