version: '2'

services:
  movie-pie-backend:
    image: s4kibs4mi/movie-pie:0.0.1
    environment:
      CONSUL_URL: "localhost:8500"
      CONSUL_PATH: "movie-pie"
    command: ["serve"]
    ports:
      - "5005:5005"
